### PR TITLE
feat: expose platform effector

### PR DESCRIPTION
**Pull request by dragoncoder047**
idk why i didn't make a PR for this 2 weeks ago...

### CODE REVIEW

**Comment by mflerackers** [comment]
Did you test the platform effector? It wasn't exported because it is completely untested.

**Comment by dragoncoder047** [comment]
> Did you test the platform effector? It wasn't exported because it is completely untested.

Can't test it without it being exported!

**Comment by mflerackers** [comment]
Yes, but you can export it locally to test it.

**Comment by dragoncoder047** [comment]
OK, I tested it and worked on it to make it work. Added 2 new examples on how to use it too.

**Comment by dragoncoder047** [comment]
@mflerackers

**Review by mflerackers — COMMENTED** [review]
shouldCollide is set as optional, but later it is said to exist, is that correct?
Shouldn't there be a default shouldCollide using the collisionSides?

**Comment by dragoncoder047** [comment]
> shouldCollide is set as optional, but later it is said to exist, is that correct? Shouldn't there be a default shouldCollide using the collisionSides?

Yes, it is lines 185-188

**Review by mflerackers — APPROVED** [review]

**Pull request merged**
