### PR TITLE
feat: add panner node into play() pipeline

### LINKED ISSUE #304: feat: Stereo pan option for `play()`
We already have a volume option for `play()`ing a sound. Can stereo pan be added? There is a web audio node to handle this, it just needs to be put in the pipeline.

This would be useful when a sound is triggered by some physical action, and it would make sense to have the sound appear to come from the location of that action. For example, if an enemy spawned offscreen to the left, the player could be cued that it is to the left by the spawn sound coming from the left speaker. (This is particularly evident when you are using headphones.)

### PR DESCRIPTION
**Pull request by dragoncoder047**
closes #304

### CODE REVIEW

**Comment by lajbel** [comment]
why is gainNode not used anymore?

**Comment by dragoncoder047** [comment]
No, is still used, source connects to pan node, pan node connects to gain node, gain connects to output.

**Review by lajbel — APPROVED** [review]

**Review by mflerackers — APPROVED** [review]

**Comment by lajbel** [comment]
you should open a PR with the same changes but for master

**Comment by dragoncoder047** [comment]
> you should open a PR with the same changes but for master

I did originally base this pr against master, you switched it!

**Comment by lajbel** [comment]
IK, what I mean is create another PR because it's a change compatible with v4000 and v3001

**Comment by lajbel** [comment]
This should be only for v3001, shouldn't merge with master

**Comment by lajbel** [comment]
is on https://github.com/kaplayjs/kaplay/blob/master/CONTRIBUTING.md

**Review by niceEli — APPROVED** [review]

**Comment by niceEli** [comment]
the error is not fault of the pr. its a pkg.pr.new issue

**Comment by lajbel** [comment]
> > IK, what I mean is create another PR because it's a change compatible with v4000 and v3001
> 
> so you mean merge this into v3001, and then do the same changes but on master?

You should replicate the same changes for every branch, master and v3001, then open 2 PR's

**Comment by dragoncoder047** [comment]
> You should replicate the same changes for every branch, master and v3001, then open 2 PR's

Ok, I switched this one back to master to keep the commit history clean, will open another pr for v3001 soon

**Comment by niceEli** [comment]
is ready for merge?

**Comment by niceEli** [comment]
btw you dont really need to worry about commit history as it just gets squashed and merged into 1 commit anyway

**Pull request merged**
