### PR TITLE
closest orthagonal distance function

### PR DESCRIPTION
**Pull request by dragoncoder047**
idk this might be useful?

### CODE REVIEW

**Review by lajbel — APPROVED** [review]
LGTM!

**Comment by imaginarny** [comment]
Wait a second. There are a few cosmetic issues. It is 'orth**O**gonal', not 'orth**A**gonal'. Also, `let` would be preferable instead of `var`, although it's not much of an issue in this particular case (probably). Just a heads-up.

**Comment by mflerackers** [comment]
Isn't this just return vec2(this.x < 0 ? left : right, this.y < 0 ? up : down) ?

**Comment by dragoncoder047** [comment]
> Isn't this just return vec2(this.x < 0 ? left : right, this.y < 0 ? up : down) ?

Not quite. It does the orthogonal direction closest to the angle of this, so say if you have vec2(-1, -10) it will return UP not LEFT.

Since it is only 4 candidates, I suspect it can be done with a bunch of conditionals, however, it made more sense to use a loop to me. :shrug: It might be *faster* to use conditionals, but until this function is used somewhere I really can't say.

**Comment by mflerackers** [comment]
So 

return Math.abs(this.x) > Math.abs(this.y) ? 
  this.x < 0 ? left : right :
  this.y < 0 ? up : down;

Two conditionals will always be faster than calculating 4 square roots (which weren't really needed, the dot product is enough to compare distances).

**Review by mflerackers — APPROVED** [review]

**Pull request merged**
